services:
  aosp-build-14:
    build:
      context: ./
      dockerfile: Dockerfile
    image: aosp-build-14
    container_name: aosp-build-14
    volumes:
      - aosp:/home/th/aosp
    stdin_open: true
    tty: true

volumes:
  aosp:
    name: aosp